/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.8/samples
 */

plugins {
	`java-library`
    id("io.papermc.paperweight.userdev") version "2.0.0-beta.14"
}

repositories {
    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }
    maven {
        url = uri("https://libraries.minecraft.net")
    }
}

dependencies {
    compileOnly("com.mojang:brigadier:1.0.18")
    implementation("commons-io:commons-io:2.7")
    paperweight.paperDevBundle("1.21.4-R0.1-SNAPSHOT")
    implementation("net.kyori:adventure-text-minimessage:4.18.0")
}

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(21))
}